# Generated by Django 5.0.6 on 2024-06-08 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_song_performer_alter_song_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="listener",
            field=models.ManyToManyField(
                related_name="listener", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
